# Generated by Django 5.1 on 2024-09-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_app_user_delete_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='user_points',
            field=models.IntegerField(default=0),
        ),
    ]
