# Generated by Django 5.1 on 2024-09-25 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='link',
            new_name='app_link',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='name',
            new_name='app_name',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='points',
            new_name='app_points',
        ),
        migrations.RenameField(
            model_name='usertask',
            old_name='app',
            new_name='app_name',
        ),
        migrations.RemoveField(
            model_name='app',
            name='description',
        ),
        migrations.AddField(
            model_name='app',
            name='app_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='app_image',
            field=models.ImageField(blank=True, null=True, upload_to='app_images/'),
        ),
        migrations.AddField(
            model_name='app',
            name='app_types',
            field=models.CharField(choices=[('EN', 'Entertainment'), ('SM', 'Social media'), ('PR', 'Productivity'), ('ED', 'Educational')], default='SM', max_length=50),
        ),
        migrations.AddField(
            model_name='app',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
