# Generated by Django 5.1 on 2024-09-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_rename_link_app_app_link_rename_name_app_app_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='app',
            name='app_types',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
