# Generated by Django 5.1 on 2024-09-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='upload',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
